<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headTitle(); ?>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="/s/main.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="/s/jquery-ui.css" type="text/css" media="screen" />
	<script src="/lib.js" type="text/javascript"></script>
</head>
<body>
<div id="page">
	<div id="header">
		<a href="/">simple ToDo</a>
	</div>
	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div> 
</div>
</body>
</html>
